name: yolo_need_app
description: A role-based, AI-powered community platform for need capture, collaboration, support, and gamified engagement.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & Network
  dio: ^5.4.0
  http: ^1.1.2
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  oauth2: ^2.0.2
  jose: ^0.3.4
  
  # Azure Integration (using standard HTTP packages for Azure REST APIs)
  # azure_core: ^0.1.1  # Removed - not available
  # microsoft_graph_api: ^1.0.0  # Removed - not available
  # signalr_netcore: ^1.3.7  # Removed - not available
  
  # UI & Theme
  material_color_utilities: ^0.11.1
  dynamic_color: ^1.6.8
  cupertino_icons: ^1.0.6
  
  # Media & File Handling
  camera: ^0.10.5+7
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  
  # Audio & Speech
  speech_to_text: ^6.6.0
  audioplayers: ^5.2.1
  permission_handler: ^11.2.0
  
  # Barcode & QR
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.5.6
  
  # Charts & Animations
  fl_chart: ^0.66.0
  rive: ^0.12.4
  lottie: ^2.7.0
  animations: ^2.0.11
  flutter_svg: ^2.0.9
  
  # Utilities
  intl: ^0.19.0
  timeago: ^3.6.0
  uuid: ^4.3.3
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # Database
  sqflite: ^2.3.2
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Vector Operations & Machine Learning
  vector_math: ^2.1.4
  ml_linalg: ^13.15.0
  
  # Graph Processing
  graphs: ^2.3.1
  collection: ^1.18.0
  
  # Semantic Search & NLP
  dart_cosine_similarity: ^0.1.1
  
  # Enhanced HTTP for embeddings
  retry: ^3.1.2
  
  # Badges & Gamification
  badges: ^3.1.2
  
  # Testing
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  riverpod_generator: ^2.3.9
  
  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700 